### PR TITLE
fix: implement logic to fetch next batch of results

### LINKED ISSUE #6: Action only fetches the first 10 items
When using the action with `recursive: true` and `paths: …` it will only fetch the first 10 items from SSM and stop. 

https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/SSM.html#getParametersByPath-property

### PR DESCRIPTION
**Pull request by jwarykowski**
## Overview 

This PR implements the logic to keep fetching until all parameters have been returned. This should resolve #6.

## Notes

Furthermore, I've moved some functionality not used and changed up the `getParameter` function to pass an object.

### CODE REVIEW

**Comment by jwarykowski** [comment]
@eliasjcjunior any chance we can get this merged soon?

**Review by eliasjcjunior — APPROVED** [review]

**Comment by jwarykowski** [comment]
Thanks for merging @eliasjcjunior, can we get this latest version published on the actions marketplace?

**Comment by eliasjcjunior** [comment]
Hey @jwarykowski I change de last version now, you can use the latest version, thanks for your help

**Comment by jwarykowski** [comment]
> Hey @jwarykowski I change de last version now, you can use the latest version, thanks for your help

Hey @eliasjcjunior, apologies, this doesn't appear to be working. After looking at the tagged version source it appears you haven't included my changes, please see the screenshot below:

Screenshot 2023-03-12 at 11 14 51 pm

If possible can you please take a look when you next get chance?

**Comment by eliasjcjunior** [comment]
@jwarykowski Sorry, I forgot to build before creating the release, I created a new version with build file updated

image

**Pull request merged**
